# Generated by Django 5.0 on 2026-02-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "current_education_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preferred_domain", models.CharField(max_length=100)),
                ("technical_skills", models.TextField(help_text="Comma-separated skills")),
                ("career_goal", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCareerAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interests", models.JSONField(default=list, help_text="Select one or more interest areas")),
                ("skills", models.JSONField(default=list, help_text="Select one or more current skills")),
                (
                    "strong_subjects",
                    models.TextField(help_text="Core academic subjects the student performs well in"),
                ),
                (
                    "financial_background",
                    models.CharField(help_text="e.g., low, middle, high income", max_length=150),
                ),
                (
                    "career_goals",
                    models.TextField(help_text="Long-term and short-term career aspirations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="career_assessments", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="StudentAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("aptitude_score", models.PositiveSmallIntegerField()),
                ("communication_score", models.PositiveSmallIntegerField()),
                ("coding_score", models.PositiveSmallIntegerField()),
                ("leadership_score", models.PositiveSmallIntegerField()),
                (
                    "interests",
                    models.TextField(help_text="Key interests, projects, and extracurricular activities"),
                ),
                (
                    "constraints",
                    models.TextField(blank=True, help_text="Any location, financial, or schedule constraints"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="roadmap.userprofile"),
                ),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
        migrations.CreateModel(
            name="CareerRecommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recommended_roles", models.JSONField(default=list)),
                ("learning_path", models.JSONField(default=list)),
                ("roadmap_summary", models.TextField()),
                ("confidence_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="recommendation", to="roadmap.studentassessment"),
                ),
            ],
            options={"ordering": ["-generated_at"]},
        ),
    ]
